dist: bionic
language: cpp

python:
  - "3.8"

addons:
  apt:
    packages:
      - g++-8
      - clang-8

before_install:
  - pip install --upgrade pip
  - pip install --user cpp-coveralls
  - pip install --user conan
  - sudo apt-get update -qq
  - sudo apt install libboost-all-dev
  - sudo apt-get install valgrind

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake .
  - cmake --build . 
  - ./gtests
  - valgrind -v --error-exitcode=42 --leak-check=full ./gtests

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
