dist: bionic
language: cpp

addons:
  apt:
    packages:
      - g++-8
      - clang-8

before_install:
  - pip install --user cpp-coveralls
  - sudo apt install libboost-all-dev

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake .
  - cmake --build . 
  - ./gtests

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
