dist: bionic
language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

python:
  - "3.8"

addons:
  apt:
    packages:
      - g++-8
      - clang-8

before_install:
  - pip install --user --upgrade pip
  - pip install --user cpp-coveralls
  - pip install --user conan
  - sudo apt update -qq
  - sudo apt install libboost-all-dev
  - sudo apt install valgrind

install:
# Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.16/cmake-3.16.3-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake .
  - ${DEPS_DIR}/cmake/bin/cmake --build .
  - ./gtests
  - valgrind -v --error-exitcode=42 --leak-check=full ./gtests

after_success:
  - coveralls --root . -E ".*CMakeFiles.*|.*_deps.*"
